theme="catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"esc" = ":w!"
"C-A-[" = { d = "goto_prev_diag", D = "goto_first_diag", f = "goto_prev_function", c = "goto_prev_comment", a = "goto_prev_parameter", t = "goto_prev_class", p = "goto_prev_paragraph", T = "goto_prev_test", g = "goto_prev_change", G = "goto_first_change", space = "add_newline_above" }
"C-A-]" = { d = "goto_next_diag", D = "goto_last_diag", f = "goto_next_function", c = "goto_next_comment", a = "goto_next_parameter", t = "goto_next_class", p = "goto_next_paragraph", T = "goto_next_test", g = "goto_next_change", G = "goto_last_change", space = "add_newline_below" }
"A-q" = [":write-all!",":q!"]
"A-w" = [":write-all!"]
"C-q" = ":write-buffer-close!"
#append remap in order to not see the selection 
"a" = ["move_prev_word_start","move_next_word_end","move_char_right","insert_mode"]
#tab remap to move between buffers
"tab" = "goto_next_buffer"
"S-tab" = "goto_previous_buffer"
#move line or selection up/down
"A-down" = ["extend_to_line_bounds","delete_selection","paste_after"]
"A-up" = ["extend_to_line_bounds","delete_selection","move_line_up","paste_before"]
#paste the line or selection up/down
"A-S-down" = ["extend_to_line_bounds","yank","paste_after"]
"A-S-up" = ["extend_to_line_bounds","yank","paste_before"]
#start the selection
"C-d" = ["keep_primary_selection", "move_prev_word_start", "move_next_word_end", "search_selection", "select_mode"]

[keys.insert]
esc = ["normal_mode",":write-all!"]
"C-right" = ["normal_mode","move_next_word_end","move_char_right","insert_mode"] 
# "C-left" = ["normal_mode","move_prev_word_start","move_char_left","move_char_right","insert_mode"] 
"C-left" = ["normal_mode","move_prev_word_start","insert_mode","move_char_right","move_char_left"] 

[keys.select]
esc = ["normal_mode",":write-all!"]
#select the next occurence of the selected text
"C-d" = ["search_selection", "extend_search_next"]
